### ISSUE TITLE
can't catch database empty result set error

### ISSUE THREAD

**Issue by byfareska** [planetteamspeak/ts3phpframework#49]
Hi. I'm trying to get client list of an channel group but if it's empty I get an error.
```
database empty result set<br><pre>#0 /home/eska/NetBeansProjects/un3/app/plugins/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/Adapter/ServerQuery/Reply.php(91): TeamSpeak3_Adapter_ServerQuery_Reply->fetchError(Object(TeamSpeak3_Helper_String))
#1 /home/eska/NetBeansProjects/un3/app/plugins/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/Adapter/ServerQuery.php(141): TeamSpeak3_Adapter_ServerQuery_Reply->__construct(Array, 'channelgroupcli...', Object(TeamSpeak3_Node_Host), true)
#2 /home/eska/NetBeansProjects/un3/app/plugins/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/Node/Abstract.php(73): TeamSpeak3_Adapter_ServerQuery->request('channelgroupcli...', true)
#3 /home/eska/NetBeansProjects/un3/app/plugins/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/Node/Server.php(90): TeamSpeak3_Node_Abstract->request('channelgroupcli...', true)
#4 /home/eska/NetBeansProjects/un3/app/plugins/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/Node/Abstract.php(97): TeamSpeak3_Node_Server->request('channelgroupcli...')
#5 /home/eska/NetBeansProjects/un3/app/plugins/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/Node/Server.php(1562): TeamSpeak3_Node_Abstract->execute('channelgroupcli...', Array)
#6 /home/eska/NetBeansProjects/un3/app/plugins/Channel/BannedList.php(51): TeamSpeak3_Node_Server->channelGroupClientList(7, 7)
#7 /home/eska/NetBeansProjects/un3/app/plugins/Channel/BannedList.php(27): Channel\BannedList->getBannedDbids()
#8 /home/eska/NetBeansProjects/un3/app/controllers/Userpanel/ChannelController.php(42): Channel\BannedList->__construct()
#9 [internal function]: Userpanel\ChannelController->bannedlistAction()
#10 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(Userpanel\ChannelController), 'bannedlistActio...', Array)
#11 [internal function]: Phalcon\Dispatcher->_dispatch()
#12 [internal function]: Phalcon\Dispatcher->dispatch()
#13 /home/eska/NetBeansProjects/un3/public/index.php(40): Phalcon\Mvc\Application->handle()
#14 {main}</pre>
```

code

```
    private function getBannedDbids() {
        try {
            foreach ($this->ts->channelGroupClientList(\Consts\Config::BANNED_CGID, $this->firstChannelId) as $value) {
                $this->bannedDbids[] = $value['cldbid'];
            }
        }
        catch (TeamSpeak3_Exception $e){}
    }

    private function getBannedUids() {
        try {
            foreach ($this->bannedDbids as $dbid) {
                $this->bannedUids[] = (string)$this->ts->clientInfoDb($dbid, true)['client_unique_identifier'];
            }
        }
        catch (TeamSpeak3_Exception $e){}
    }
```

**Comment by ronindesign** [comment]
Hi @byfareska, thanks for the message. Let me review this and get back to you.

**Comment by ronindesign** [comment]
Looks like this should return an array, so you shouldn't get an error.
Ref: https://docs.planetteamspeak.com/ts3/php/framework/class_team_speak3___node___server.html#a1a38a8600cfc3b18f7c494dede3d4f0b

If you pull the line in your foreach out, do you still get an error on empty result? Example:
```php
$this->ts->channelGroupClientList(\Consts\Config::BANNED_CGID, $this->firstChannelId)
```
Does this return error?

**Comment by ronindesign** [comment]
Looks like `database empty result set` is an error directly from the TeamSpeak3 Server Query command.

I'll look into this further to make sure the right error results are being produced by the framework.

**Comment by ronindesign** [comment]
Closing since I haven't heard anything recently. 

Please feel free to comment if you're still have an issue.
