### ISSUE TITLE
URI error - Query-Password contains question marks

### ISSUE THREAD

**Issue by Newcomer1989** [planetteamspeak/ts3phpframework#63]
The connection URI will be build wrong, if the password contains a **question mark**.

Example PHP Code to build up the connection:
`$ts3 = TeamSpeak3::factory("serverquery://".$tsuser.":".$tspass."@".$tshost.":".$tsquery."/?server_port=".$tsvoice."&blocking=0");`

Example values:
`$tspass = 34j5?4352`
`TeamSpeak3::factory("serverquery://serveradmin:34j5?4352@localhost:10011/?server_port=9987&blocking=0")`

Getting this error:
`php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution`

How to escape the question marks in the right way?

Using:
Framework Version: 1.1.24
But should be the same on the actual pre-Release 1.1.28 (Helper/Uri.php seems not be changed at this point)
PHP Version: 7.1.11-0ubtunu0.17.10.1 (cli) (built: Nov  1 2017 16:30:52) ( NTS )

**Comment by jens1o** [comment]
Could you try using `\?`?

**Comment by Newcomer1989** [comment]
I tried to escape it in this way, sure.. but it didn't helped
`$tspass = 34j5\?4352`

**Comment by Newcomer1989** [comment]
friendly reminder :-)

**Comment by ronindesign** [comment]
Ah, thank you for the reminder. This fell through the cracks. Looking into it.

**Comment by ronindesign** [comment]
For future reference / context:

```php
PHP Fatal error:  Uncaught TeamSpeak3_Transport_Exception: php_network_getaddresses: getaddrinfo failed: Name or service not known in /mnt/c/dev/ts3phpframework/libraries/TeamSpeak3/Transport/TCP.php:54
Stack trace:
#0 /mnt/c/dev/ts3phpframework/libraries/TeamSpeak3/Transport/TCP.php(108): TeamSpeak3_Transport_TCP->connect()
#1 /mnt/c/dev/ts3phpframework/libraries/TeamSpeak3/Adapter/ServerQuery.php(76): TeamSpeak3_Transport_TCP->readLine()
#2 /mnt/c/dev/ts3phpframework/libraries/TeamSpeak3/Adapter/Abstract.php(60): TeamSpeak3_Adapter_ServerQuery->syn()
#3 /mnt/c/dev/ts3phpframework/libraries/TeamSpeak3/TeamSpeak3.php(322): TeamSpeak3_Adapter_Abstract->__construct(Array) #4 /mnt/c/dev/ts3phpframework/test.php(10): TeamSpeak3::factory(Object(TeamSpeak3_Helper_Uri))
#5 {main}
  thrown in /mnt/c/dev/ts3phpframework/libraries/TeamSpeak3/Transport/TCP.php on line 54

Fatal error: Uncaught TeamSpeak3_Transport_Exception: php_network_getaddresses: getaddrinfo failed: Name or service not known in /mnt/c/dev/ts3phpframework/libraries/TeamSpeak3/Transport/TCP.php:54
Stack trace:
#0 /mnt/c/dev/ts3phpframework/libraries/TeamSpeak3/Transport/TCP.php(108): TeamSpeak3_Transport_TCP->connect()
#1 /mnt/c/dev/ts3phpframework/libraries/TeamSpeak3/Adapter/ServerQuery.php(76): TeamSpeak3_Transport_TCP->readLine()
#2 /mnt/c/dev/ts3phpframework/libraries/TeamSpeak3/Adapter/Abstract.php(60): TeamSpeak3_Adapter_ServerQuery->syn()
#3 /mnt/c/dev/ts3phpframework/libraries/TeamSpeak3/TeamSpeak3.php(322): TeamSpeak3_Adapter_Abstract->__construct(Array) #4 /mnt/c/dev/ts3phpframework/test.php(10): TeamSpeak3::factory(Object(TeamSpeak3_Helper_Uri))
#5 {main}
  thrown in /mnt/c/dev/ts3phpframework/libraries/TeamSpeak3/Transport/TCP.php on line 54
```
