### ISSUE TITLE
Updated Teamspeak to 3.3

### ISSUE THREAD

**Issue by realKitsune** [planetteamspeak/ts3phpframework#92]
Hey :)

I've updated my Teamspeak Server **from 3.0.16 to 3.3** since Teamspeak client will update to 3.2 today and won't accept TS3 server equal or below version 3.0.18 anymore.
Now that I'm on 3.3, my webconsole that I made shows an empty page and doesn't load my server data anymore.
Query username and password are correct.

Any idea?
![website](https://user-images.githubusercontent.com/40115017/44031054-076b8954-9f03-11e8-9e6e-f80e4282224b.png)

**Comment by realKitsune** [comment]
Here is the php errors: 

> Notice: Undefined index: PHP_AUTH_USER in /var/www/include/php/login2teamspeak.php on line 14
> 
> Fatal error: Uncaught exception 'TeamSpeak3_Adapter_ServerQuery_Exception' with message 'database empty result set' in /var/www/ts3phpframework/libraries/TeamSpeak3/Adapter/ServerQuery/Reply.php:319 Stack trace: #0 /var/www/ts3phpframework/libraries/TeamSpeak3/Adapter/ServerQuery/Reply.php(91): TeamSpeak3_Adapter_ServerQuery_Reply->fetchError(Object(TeamSpeak3_Helper_String)) #1 /var/www/ts3phpframework/libraries/TeamSpeak3/Adapter/ServerQuery.php(141): TeamSpeak3_Adapter_ServerQuery_Reply->__construct(Array, 'banlist', Object(TeamSpeak3_Node_Host), true) #2 /var/www/ts3phpframework/libraries/TeamSpeak3/Node/Abstract.php(73): TeamSpeak3_Adapter_ServerQuery->request('banlist', true) #3 /var/www/ts3phpframework/libraries/TeamSpeak3/Node/Server.php(90): TeamSpeak3_Node_Abstract->request('banlist', true) #4 /var/www/ts3phpframework/libraries/TeamSpeak3/Node/Server.php(2078): TeamSpeak3_Node_Server->request('banlist') #5 /var/www/include/php/config_global.php(7): TeamSpeak3_Node_Server->banList() #6 /var/www/include/php/header in /var/www/ts3phpframework/libraries/TeamSpeak3/Adapter/ServerQuery/Reply.php on line 319

**Comment by realKitsune** [comment]
Nvm, that was because banlist was empty.
BUT, I have a new error now:

> Fatal error: Uncaught exception 'TeamSpeak3_Adapter_ServerQuery_Exception' with message 'invalid group ID' in /var/www/ts3phpframework/libraries/TeamSpeak3/Adapter/ServerQuery/Reply.php:319 Stack trace: #0 /var/www/ts3phpframework/libraries/TeamSpeak3/Adapter/ServerQuery/Reply.php(91): TeamSpeak3_Adapter_ServerQuery_Reply->fetchError(Object(TeamSpeak3_Helper_String)) #1 /var/www/ts3phpframework/libraries/TeamSpeak3/Adapter/ServerQuery.php(141): TeamSpeak3_Adapter_ServerQuery_Reply->__construct(Array, 'servergroupclie...', Object(TeamSpeak3_Node_Host), true) #2 /var/www/ts3phpframework/libraries/TeamSpeak3/Node/Abstract.php(73): TeamSpeak3_Adapter_ServerQuery->request('servergroupclie...', true) #3 /var/www/ts3phpframework/libraries/TeamSpeak3/Node/Server.php(90): TeamSpeak3_Node_Abstract->request('servergroupclie...', true) #4 /var/www/ts3phpframework/libraries/TeamSpeak3/Node/Abstract.php(97): TeamSpeak3_Node_Server->request('servergroupclie...') #5 /var/www/ts3phpframework/libraries/TeamSpeak3/Node/Server.php(1230): Tea in /var/www/ts3phpframework/libraries/TeamSpeak3/Adapter/ServerQuery/Reply.php on line 319

**Comment by realKitsune** [comment]
Okay I close it, it's just that my update completely messed up my server(bans, groups ids, ...)
Thought it was because of an incompatibility of api and new version.

Sorry
